apiVersion: apps/v1
kind: Deployment
metadata:
  name: secopstest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secopstest
  template:
    metadata:
      labels:
        app: secopstest
    spec:
      containers:
      - name: secopstest
        image: 985261590416.dkr.ecr.us-west-2.amazonaws.com/secopstest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secopstest
    k8s-app: secopstest
  name: secopstest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: secopstest
